name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  riverpod_hook_mutation:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

scripts:
  g:
    $script: rps gen build
    $description: shortcut for gen build
  w:
    $script: rps gen watch
    $description: shortcut for gen watch

  get:
    $script: fvm flutter pub get
    $description: Get dependencies

  gen:
    watch:
      $script: fvm dart run build_runner watch --delete-conflicting-outputs
      $description: Generate files on save
    build:
      $script: fvm dart run build_runner build --delete-conflicting-outputs
      $description: Generate files

  fix-format:
    $script: fvm dart fix --apply && fvm dart format -o write ./lib
    $description: Fix code warnings and format code
